[2023-07-22T06:57:03.738+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_final_project.load_gcs_to_bq manual__2023-07-22T06:50:35.340426+00:00 [queued]>
[2023-07-22T06:57:03.773+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_final_project.load_gcs_to_bq manual__2023-07-22T06:50:35.340426+00:00 [queued]>
[2023-07-22T06:57:03.773+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-22T06:57:03.845+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bq> on 2023-07-22 06:50:35.340426+00:00
[2023-07-22T06:57:03.914+0000] {standard_task_runner.py:57} INFO - Started process 596 to run task
[2023-07-22T06:57:04.063+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'load_gcs_to_bq', 'manual__2023-07-22T06:50:35.340426+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmpjkkvly8l']
[2023-07-22T06:57:04.238+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask load_gcs_to_bq
[2023-07-22T06:57:04.345+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-22T06:57:04.562+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_final_project.load_gcs_to_bq manual__2023-07-22T06:50:35.340426+00:00 [running]> on host 0fc5064484a4
[2023-07-22T06:57:04.918+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_final_project' AIRFLOW_CTX_TASK_ID='load_gcs_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2023-07-22T06:50:35.340426+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-22T06:50:35.340426+00:00'
[2023-07-22T06:57:04.947+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 319, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 112, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `bigquery_default` isn't defined
[2023-07-22T06:57:04.958+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=data_ingestion_final_project, task_id=load_gcs_to_bq, execution_date=20230722T065035, start_date=20230722T065703, end_date=20230722T065704
[2023-07-22T06:57:04.980+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 18 for task load_gcs_to_bq (The conn_id `bigquery_default` isn't defined; 596)
[2023-07-22T06:57:05.033+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-22T06:57:05.077+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
