[2023-07-22T11:19:40.547+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:19:40.551+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_database_sqlite_dag.py for tasks to queue
[2023-07-22T11:19:40.571+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:19:40.570+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:19:40.698+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:19:40.695+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_database_sqlite_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_database_sqlite_dag.py", line 15, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:19:40.699+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:19:40.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_database_sqlite_dag.py took 0.242 seconds
[2023-07-22T11:20:11.581+0000] {processor.py:157} INFO - Started process (PID=295) to work on /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:20:11.583+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_database_sqlite_dag.py for tasks to queue
[2023-07-22T11:20:11.586+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:11.585+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:20:11.637+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:11.633+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_database_sqlite_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_database_sqlite_dag.py", line 15, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:20:11.638+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:20:11.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_database_sqlite_dag.py took 0.106 seconds
[2023-07-22T11:20:42.125+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:20:42.135+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_database_sqlite_dag.py for tasks to queue
[2023-07-22T11:20:42.141+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:42.136+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:20:42.227+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:42.207+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_database_sqlite_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_database_sqlite_dag.py", line 15, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:20:42.240+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:20:42.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_database_sqlite_dag.py took 0.152 seconds
[2023-07-22T11:21:13.340+0000] {processor.py:157} INFO - Started process (PID=354) to work on /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:21:13.346+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_database_sqlite_dag.py for tasks to queue
[2023-07-22T11:21:13.354+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:21:13.348+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:21:13.436+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:21:13.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_database_sqlite_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_database_sqlite_dag.py", line 15, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:21:13.437+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_database_sqlite_dag.py
[2023-07-22T11:21:13.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_database_sqlite_dag.py took 0.160 seconds
