[2023-07-22T04:23:22.690+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_final_project.load_gcs_to_bq manual__2023-07-22T04:15:21.245137+00:00 [queued]>
[2023-07-22T04:23:22.717+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_final_project.load_gcs_to_bq manual__2023-07-22T04:15:21.245137+00:00 [queued]>
[2023-07-22T04:23:22.720+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-22T04:23:22.758+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bq> on 2023-07-22 04:15:21.245137+00:00
[2023-07-22T04:23:22.773+0000] {standard_task_runner.py:57} INFO - Started process 915 to run task
[2023-07-22T04:23:22.809+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'load_gcs_to_bq', 'manual__2023-07-22T04:15:21.245137+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmpdp5nhc1s']
[2023-07-22T04:23:22.839+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask load_gcs_to_bq
[2023-07-22T04:23:23.061+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-22T04:23:23.189+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_final_project.load_gcs_to_bq manual__2023-07-22T04:15:21.245137+00:00 [running]> on host 4f08e73380e0
[2023-07-22T04:23:23.406+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_final_project' AIRFLOW_CTX_TASK_ID='load_gcs_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2023-07-22T04:15:21.245137+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-22T04:15:21.245137+00:00'
[2023-07-22T04:23:23.465+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 319, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 112, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `bigquery_default` isn't defined
[2023-07-22T04:23:23.482+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=data_ingestion_final_project, task_id=load_gcs_to_bq, execution_date=20230722T041521, start_date=20230722T042322, end_date=20230722T042323
[2023-07-22T04:23:23.524+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task load_gcs_to_bq (The conn_id `bigquery_default` isn't defined; 915)
[2023-07-22T04:23:23.592+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-22T04:23:23.743+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
