[0m23:41:41.692733 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa944fe48e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa943519c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa943519b50>]}


============================== 23:41:41.697460 | 1f279cc4-cb1a-4827-b65a-fca586c614aa ==============================
[0m23:41:41.697460 [info ] [MainThread]: Running with dbt=1.5.3
[0m23:41:41.697995 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/azril/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m23:41:41.699227 [debug] [MainThread]: Starter project path: /home/azril/marketing/test/lib/python3.8/site-packages/dbt/include/starter_project
[0m23:47:41.726272 [error] [MainThread]: Encountered an error:

[0m23:47:41.734401 [error] [MainThread]: Traceback (most recent call last):
  File "/home/azril/marketing/test/lib/python3.8/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/azril/marketing/test/lib/python3.8/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/home/azril/marketing/test/lib/python3.8/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
  File "/home/azril/marketing/test/lib/python3.8/site-packages/dbt/task/init.py", line 307, in run
    self.create_profile_from_target(adapter, profile_name=project_name)
  File "/home/azril/marketing/test/lib/python3.8/site-packages/dbt/task/init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/azril/marketing/test/lib/python3.8/site-packages/dbt/task/init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/azril/marketing/test/lib/python3.8/site-packages/dbt/task/init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
  File "/home/azril/marketing/test/lib/python3.8/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/home/azril/marketing/test/lib/python3.8/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m23:47:41.735665 [debug] [MainThread]: Command `dbt init` failed at 23:47:41.735520 after 360.06 seconds
[0m23:47:41.736080 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa944fe48e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa94353ecd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa92b4ef760>]}
[0m23:47:41.736525 [debug] [MainThread]: Flushing usage events
